extends Modal
## Attribution for the art in use. LPC licenses (CC-BY-SA, OGA-BY, GPL...)
## require crediting every author; this lists the authors of every part the
## account's characters are wearing, plus the general LPC statement.

func _init() -> void:
	super("Credits")

func _ready() -> void:
	super()
	body.add_child(UiKit.para("Character art: Liberated Pixel Cup (LPC) contributors, from OpenGameArt.org via the Universal LPC Spritesheet Character Generator. Licenses: CC-BY-SA 3.0/4.0, CC-BY, OGA-BY 3.0, GPL 3.0, CC0 (per part). Full list: github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/CREDITS.csv", 15, UiKit.TEXT))
	body.add_child(UiKit.para("Interface icons: game-icons.net by Lorc, Delapouite, Sbed and Zeromancer (CC BY 3.0), recoloured. Monsters, item icons and tiles are generated by the game. Font: Vazirmatn (SIL Open Font License).", 15, UiKit.MUTED))
	var seen := {}
	for ch in Game.characters:
		var r := await Api.get_json("/v1/sprites/credits?r=" + Sprites.encode_recipe(ch.appearance))
		if not r.ok:
			continue
		for c in r.data.credits:
			var key := str(c.file)
			if seen.has(key):
				continue
			seen[key] = true
			body.add_child(UiKit.para("%s: %s (%s)" % [key, ", ".join(PackedStringArray(c.authors)), ", ".join(PackedStringArray(c.licenses))], 13, UiKit.MUTED))
